name: 02 - Workflow Events

on:
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the triggerrrrrrrrrrrrrrrrrrrrrrrr
        run: echo "I've beennnnnnn triggered by a(n) ${{ github.event_name }} event."
