name: 02 - Workflow Events

on:
  pull:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've beennnnnnn triggered by a(n) ${{ github.event_name }} event."
